name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Clean Publish Folder
      run: |
        if (Test-Path "C:\temp\publish") {
          Remove-Item "C:\temp\publish" -Recurse -Force -ErrorAction SilentlyContinue
        }

    - name: Publish Project
      run: dotnet publish -c Release -o C:\temp\publish

    - name: Deploy to IIS Folder
      run: |
        robocopy C:\temp\publish C:\WebApp\CICD /MIR /R:1 /W:1

    - name: Done
      run: echo "Deploy Success"
